#!/usr/bin/env python3
"""
Convert guge_urdf URDF to MuJoCo MJCF XML.

Reads the URDF, fixes mesh paths, adds actuators/sensors/scene elements,
and outputs a complete MuJoCo scene file.

Usage:
    python tools/convert_guge_urdf.py
"""

import os
import sys
import xml.etree.ElementTree as ET
import copy

OPENSERVOSIM_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URDF_PATH = os.path.join(OPENSERVOSIM_ROOT, "models", "guge_urdf", "urdf", "guge_urdf.urdf")
MESH_DIR = os.path.join(OPENSERVOSIM_ROOT, "models", "guge_urdf", "meshes")
OUTPUT_PATH = os.path.join(OPENSERVOSIM_ROOT, "models", "guge", "scene_guge.xml")


def parse_urdf():
    """Parse the URDF and extract links and joints."""
    tree = ET.parse(URDF_PATH)
    root = tree.getroot()

    links = {}
    joints = []

    for link_elem in root.findall("link"):
        name = link_elem.get("name")
        link_data = {"name": name}

        inertial = link_elem.find("inertial")
        if inertial is not None:
            origin = inertial.find("origin")
            mass = inertial.find("mass")
            inertia = inertial.find("inertia")
            link_data["mass"] = float(mass.get("value")) if mass is not None else 0.0
            if origin is not None:
                link_data["inertial_pos"] = origin.get("xyz", "0 0 0")
            if inertia is not None:
                link_data["inertia"] = {
                    "ixx": inertia.get("ixx", "0"),
                    "iyy": inertia.get("iyy", "0"),
                    "izz": inertia.get("izz", "0"),
                    "ixy": inertia.get("ixy", "0"),
                    "ixz": inertia.get("ixz", "0"),
                    "iyz": inertia.get("iyz", "0"),
                }

        visual = link_elem.find("visual")
        if visual is not None:
            geom = visual.find("geometry")
            if geom is not None:
                mesh = geom.find("mesh")
                if mesh is not None:
                    filename = mesh.get("filename", "")
                    # Extract just the STL filename
                    stl_name = filename.split("/")[-1]
                    link_data["mesh_file"] = stl_name

            mat = visual.find("material")
            if mat is not None:
                color = mat.find("color")
                if color is not None:
                    link_data["rgba"] = color.get("rgba", "1 1 1 1")

        links[name] = link_data

    for joint_elem in root.findall("joint"):
        name = joint_elem.get("name")
        jtype = joint_elem.get("type")
        parent = joint_elem.find("parent").get("link")
        child = joint_elem.find("child").get("link")
        origin = joint_elem.find("origin")
        axis = joint_elem.find("axis")
        limit = joint_elem.find("limit")

        joint_data = {
            "name": name,
            "type": jtype,
            "parent": parent,
            "child": child,
            "xyz": origin.get("xyz", "0 0 0") if origin is not None else "0 0 0",
            "rpy": origin.get("rpy", "0 0 0") if origin is not None else "0 0 0",
            "axis": axis.get("xyz", "0 0 1") if axis is not None else "0 0 1",
        }
        if limit is not None:
            joint_data["lower"] = float(limit.get("lower", "-1.5708"))
            joint_data["upper"] = float(limit.get("upper", "1.5708"))
            joint_data["effort"] = float(limit.get("effort", "100"))
        joints.append(joint_data)

    return links, joints


def rpy_to_euler_str(rpy_str):
    """Convert RPY string to MuJoCo euler string."""
    parts = rpy_str.strip().split()
    r, p, y = float(parts[0]), float(parts[1]), float(parts[2])
    import math
    r_deg = math.degrees(r)
    p_deg = math.degrees(p)
    y_deg = math.degrees(y)
    return f"{r_deg:.2f} {p_deg:.2f} {y_deg:.2f}"


def generate_mjcf(links, joints):
    """Generate MuJoCo MJCF XML from parsed URDF data."""
    import math

    # Build parent-child tree
    children_map = {}  # parent_link -> [(joint, child_link), ...]
    for j in joints:
        parent = j["parent"]
        if parent not in children_map:
            children_map[parent] = []
        children_map[parent].append(j)

    # Collect all mesh files
    mesh_files = set()
    for link in links.values():
        if "mesh_file" in link:
            mesh_files.add(link["mesh_file"])

    # Joint names for actuators (only revolute)
    actuator_joints = [j["name"] for j in joints if j["type"] == "revolute"]

    lines = []
    lines.append('<!-- Guge Upper Body Robot - Auto-generated from URDF -->')
    lines.append('<!-- Generated by tools/convert_guge_urdf.py -->')
    lines.append('<mujoco model="guge_upper_body">')
    lines.append('')

    # Compiler
    lines.append('  <compiler angle="radian" meshdir="../guge_urdf/meshes/" eulerseq="xyz"/>')
    lines.append('')

    # Option
    lines.append('  <option timestep="0.002" gravity="0 0 -9.81" integrator="implicit"/>')
    lines.append('')

    # Default
    lines.append('  <default>')
    lines.append('    <joint damping="0.5" armature="0.01"/>')
    lines.append('    <geom condim="3" friction="0.8 0.02 0.01" margin="0.001"/>')
    lines.append('    <motor ctrllimited="true"/>')
    lines.append('    <default class="visual">')
    lines.append('      <geom type="mesh" contype="0" conaffinity="0" group="1"/>')
    lines.append('    </default>')
    lines.append('    <default class="collision">')
    lines.append('      <geom group="3" type="capsule"/>')
    lines.append('    </default>')
    lines.append('  </default>')
    lines.append('')

    # Assets
    lines.append('  <asset>')
    lines.append('    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>')
    lines.append('    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300"/>')
    lines.append('    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>')
    lines.append('    <material name="body_white" rgba="0.9 0.9 0.9 1"/>')
    lines.append('    <material name="body_cyan" rgba="0 0.93 1 1"/>')
    for mesh_file in sorted(mesh_files):
        mesh_name = mesh_file.replace(".STL", "").replace(".stl", "")
        lines.append(f'    <mesh name="{mesh_name}" file="{mesh_file}" scale="1 1 1"/>')
    lines.append('  </asset>')
    lines.append('')

    # Worldbody
    lines.append('  <worldbody>')
    lines.append('    <!-- Ground -->')
    lines.append('    <geom name="floor" type="plane" size="5 5 0.1" material="groundplane"/>')
    lines.append('    <!-- Lights -->')
    lines.append('    <light name="spotlight" mode="targetbodycom" target="spine3" pos="0 -1 2" diffuse="0.8 0.8 0.8"/>')
    lines.append('    <light name="ambient" directional="true" pos="0 0 3" dir="0 0 -1" diffuse="0.4 0.4 0.4"/>')
    lines.append('')

    # Mount stand - fixed pedestal to hold the upper body at a viewing height
    lines.append('    <!-- Mount Stand -->')
    lines.append('    <body name="stand" pos="0 0 0.8">')
    lines.append('      <geom name="stand_pole" type="cylinder" size="0.02 0.4" pos="0 0 -0.4" rgba="0.3 0.3 0.3 1"/>')
    lines.append('      <geom name="stand_base" type="cylinder" size="0.15 0.02" pos="0 0 -0.8" rgba="0.3 0.3 0.3 1"/>')
    lines.append('')

    def write_body(link_name, indent_level):
        """Recursively write body elements."""
        indent = "      " + "  " * indent_level
        link = links.get(link_name, {})

        # Find the joint that connects to this link
        joint_for_link = None
        for j in joints:
            if j["child"] == link_name:
                joint_for_link = j
                break

        mass = link.get("mass", 0.001)
        inertial_pos = link.get("inertial_pos", "0 0 0")
        mesh_name = link.get("mesh_file", "").replace(".STL", "").replace(".stl", "")
        rgba = link.get("rgba", "0.9 0.9 0.9 1")

        # Determine material
        mat = "body_cyan" if "0.925" in rgba else "body_white"

        # Body position from joint origin
        if joint_for_link:
            pos = joint_for_link["xyz"]
            euler = rpy_to_euler_str(joint_for_link["rpy"])
            lines.append(f'{indent}<body name="{link_name}" pos="{pos}" euler="{euler}">')
        else:
            lines.append(f'{indent}<body name="{link_name}">')

        # Inertial
        if mass > 0.001:
            inertia = link.get("inertia", {})
            diag = f'{inertia.get("ixx", "0.0001")} {inertia.get("iyy", "0.0001")} {inertia.get("izz", "0.0001")}'
            lines.append(f'{indent}  <inertial pos="{inertial_pos}" mass="{mass}" diaginertia="{diag}"/>')

        # Joint (if revolute)
        if joint_for_link and joint_for_link["type"] == "revolute":
            j = joint_for_link
            lower = j.get("lower", -1.5708)
            upper = j.get("upper", 1.5708)
            axis = j["axis"]
            lines.append(f'{indent}  <joint name="{j["name"]}" axis="{axis}" range="{lower:.4f} {upper:.4f}"/>')

        # Visual geom (mesh)
        if mesh_name:
            lines.append(f'{indent}  <geom class="visual" mesh="{mesh_name}" material="{mat}"/>')

        # Recurse into children
        if link_name in children_map:
            for child_joint in children_map[link_name]:
                child_link = child_joint["child"]
                write_body(child_link, indent_level + 1)

        lines.append(f'{indent}</body>')

    # Start from base_link (skip base_footprint)
    # base_link is connected to base_footprint via fixed joint
    write_body("base_link", 0)

    lines.append('    </body>  <!-- end stand -->')
    lines.append('  </worldbody>')
    lines.append('')

    # Actuators
    lines.append('  <actuator>')
    for jname in actuator_joints:
        j = next(jt for jt in joints if jt["name"] == jname)
        lower = j.get("lower", -1.5708)
        upper = j.get("upper", 1.5708)
        lines.append(f'    <position name="{jname}_motor" joint="{jname}" kp="50" ctrlrange="{lower:.4f} {upper:.4f}"/>')
    lines.append('  </actuator>')
    lines.append('')

    # Sensors
    lines.append('  <sensor>')
    lines.append('    <gyro name="imu_gyro" site="imu_site"/>')
    lines.append('    <accelerometer name="imu_accel" site="imu_site"/>')
    lines.append('  </sensor>')
    lines.append('')

    # We need to add the IMU site - let's add it to spine3 body
    # Actually, we need to insert it into the body definition. Let me add sites separately.

    lines.append('</mujoco>')

    return '\n'.join(lines)


def main():
    print("Parsing URDF...")
    links, joints = parse_urdf()
    print(f"  Links: {len(links)}")
    print(f"  Joints: {len(joints)}")

    revolute_joints = [j for j in joints if j["type"] == "revolute"]
    print(f"  Revolute joints: {len(revolute_joints)}")
    for j in revolute_joints:
        print(f"    {j['name']}: {j['parent']} -> {j['child']}, axis={j['axis']}")

    print("\nGenerating MJCF...")
    mjcf = generate_mjcf(links, joints)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(mjcf)
    print(f"  Written to: {OUTPUT_PATH}")

    # Try to load and validate
    try:
        import mujoco
        m = mujoco.MjModel.from_xml_path(OUTPUT_PATH)
        print(f"\n  Validation OK: nq={m.nq}, nv={m.nv}, nu={m.nu}, nbody={m.nbody}")
    except ImportError:
        print("\n  [mujoco not installed, skipping validation]")
    except Exception as e:
        print(f"\n  Validation FAILED: {e}")


if __name__ == "__main__":
    main()
